name: "[Analysis] TFSec PR feedback"

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.tf"

permissions:
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  tfsec:
    name: TFSec Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: tfsec with pr comments
        uses: tfsec/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
