name: "[Analysis] Snyk IAC GitHub Security"
on:
  push:
    branches: [ main, master ]
    paths:
      - "**.tf"
  schedule:
    # 7am every wednesday
    - cron: '0 7 * * 3'

permissions:
  security-events: write
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  snyk_iac:
    name: Snyk IAC analysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Snyk IAC sarif upload
        run: echo "::warning title=MISSING-IAC-SCAN::Please add the snyk iac scan composite action when it is available."

      # TODO: Add Snyk IAC scan and upload results to GitHub Security tab when the composite action is available.

      # - name: Upload Snyk IAC scan results to GitHub Security tab
      #   id: snyk_upload_sarif
      #   uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
      #   if: always()
      #   with:
      #     category: "Terraform"
      #     sarif_file: "test-results/snyk-iac.sarif"
